version: '3.8'
services:
  ecommerce-app:
    build: .
    ports:
      - "8080:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ecommerce
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql